title = "CoderDojo 瀬戸"
baseURL = "https://coderdojo-seto.github.io"
languageCode = "ja"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "CoderDojo瀬戸 - 愛知県瀬戸市の子供向けプログラミング道場"
  facebook = ""
  twitter = "https://twitter.com/ichiroc"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/eye-catch.jpg"
  recent_posts_number = 3
